export const SET_RECIPES = 'SET_RECIPES';
export const SET_RECIPE = 'SET_RECIPE';
export const ADD_RECIPE = 'ADD_RECIPE';
export const REMOVE_RECIPE = 'REMOVE_RECIPE';
export const SET_FAVORITE = 'SET_FAVORITE';
export const UPDATE_FAVORITE = 'UPDATE_FAVORITE';
export const SET_FAVORITES = 'SET_FAVORITES';
export const SET_INGREDIENT_RECIPES = 'SET_INGREDIENT_RECIPES';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_LOADING = 'SET_LOADING';
export const SET_DETAIL_LOADING = 'SET_LOADING';
export const SET_PICKER = 'SET_PICKER';
//Home Page

export const FETCH_RECIPES = 'FETCH_RECIPES';
export const FETCH_RECIPE = 'FETCH_RECIPE';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_FAVORITES = 'FETCH_FAVORITES';
